FILETYPE_TO_EXT = {
    # base
    "python": "py",
    "javascript": "js",
    "typescript": "ts",
    "text": "txt",
    "txflow": "txf",
    "draft": "draft",
    # web frameworks & ecosystems
    "react": "jsx",
    "react-typescript": "tsx",
    "next": "tsx",
    "nextjs": "tsx",
    "remix": "tsx",
    "preact": "jsx",
    "solid": "tsx",
    "qwik": "tsx",
    "nuxt": "vue",
    "sveltekit": "svelte",
    "angular": "ts",
    "nest": "ts",
    "nestjs": "ts",
    "deno": "ts",
    "express": "js",
    "koa": "js",
    "hapi": "js",
    "sails": "js",
    "adonis": "ts",
    "react-native": "tsx",
    "gatsby": "jsx",
    "eleventy": "njk",
    "astrojs": "astro",
    "tailwind": "css",  # Tailwind source is CSS (plus config files)
    "webpack": "js",
    "vite": "ts",
    # python web frameworks
    "django": "py",
    "flask": "py",
    "fastapi": "py",
    # templating (non-identity only)
    "handlebars": "hbs",
    "nunjucks": "njk",
    "jinja": "j2",
    "jinja2": "j2",
    # css tooling (avoid identity like scss/sass/less)
    "postcss": "css",
    # databases & query languages
    "postgres": "sql",
    "postgresql": "sql",
    "mysql": "sql",
    "mariadb": "sql",
    "sqlite": "sql",  # query files; database files often use .sqlite/.db
    "duckdb": "sql",
    "redshift": "sql",
    "bigquery": "sql",
    "snowflake": "sql",
    "mssql": "sql",
    "tsql": "sql",
    "oracle": "sql",
    "plsql": "sql",
    "db2": "sql",
    "clickhouse": "sql",
    "trino": "sql",
    "presto": "sql",
    "timescaledb": "sql",
    "questdb": "sql",
    "cassandra": "cql",
    "neo4j": "cypher",
    "mongodb": "bson",  # dumps; shell scripts are often .js
    "dynamodb": "json",
    "elasticsearch": "json",
    "firestore": "json",
    "influxdb": "flux",
    # infra / config
    "graphql": "gql",
    "terraform": "tf",
    "starlark": "bzl",
    "dotenv": "env",
    "kubernetes": "yaml",
    "helm": "yaml",
    "cloudformation": "yaml",
    "ansible": "yaml",
    "openapi": "yaml",
    "nginx": "conf",
    "apache": "conf",
    # docs / markup
    "latex": "tex",
    "markdown": "md",
    "restructuredtext": "rst",
    "typst": "typ",
    "protobuf": "proto",
    # hardware / HDL
    "verilog": "v",
    "systemverilog": "sv",
    "vhdl": "vhd",
}

# 1) Filetypes → canonical extensions (duplicates removed)


# 2) Plain list of extension tokens (deduped, expanded)
EXT_TOKENS = [
    # code & scripting
    "py",
    "pyw",
    "js",
    "mjs",
    "jsx",
    "ts",
    "tsx",
    "sh",
    "bash",
    "ps1",
    "bat",
    "cmd",
    "rb",
    "php",
    "go",
    "java",
    "kt",
    "kts",
    "scala",
    "swift",
    "rs",
    "cs",
    "vb",
    "c",
    "cpp",
    "cc",
    "cxx",
    "c++",
    "h",
    "hpp",
    "r",
    "jl",
    "pl",
    "pm",
    "hs",
    "erl",
    "ex",
    "exs",
    "clj",
    "cljs",
    "edn",
    "dart",
    "lua",
    "m",
    "mm",
    "mat",
    "v",
    "sv",
    "vhd",
    # web & markup
    "html",
    "htm",
    "css",
    "xml",
    "json",
    "yml",
    "yaml",
    "ini",
    "toml",
    "cfg",
    "conf",
    "env",
    "md",
    "markdown",
    "mdown",
    "rst",
    "tex",
    "typ",
    "typst",
    "log",
    # notebooks, data & db
    "ipynb",
    "csv",
    "tsv",
    "sql",
    "sqlite",
    "db",
    "parquet",
    "feather",
    "avro",
    "orc",
    "yb",
    "br",
    # docs & presentations
    "pdf",
    "doc",
    "docx",
    "xls",
    "xlsx",
    "ppt",
    "pptx",
    # archives & packages
    "zip",
    "tar",
    "gz",
    "bz2",
    "xz",
    "7z",
    "rar",
    # images & vector
    "jpg",
    "jpeg",
    "jpe",
    "png",
    "gif",
    "bmp",
    "tif",
    "tiff",
    "svg",
    "webp",
    "ico",
    "heic",
    # audio
    "mp3",
    "wav",
    "flac",
    "m4a",
    "ogg",
    "aac",
    "wma",
    # video
    "mp4",
    "mkv",
    "webm",
    "mov",
    "avi",
    "m4v",
    "3gp",
    # fonts
    "ttf",
    "otf",
    "woff",
    "woff2",
    "eot",
    # 3D / CAD
    "obj",
    "fbx",
    "glb",
    "gltf",
    "stl",
    "template",
    "log",
    "note",
    "skill",
    'jsonl'
]


EXTENSIONS = list(set(EXT_TOKENS + list(FILETYPE_TO_EXT.values())))
FILETYPES = list(FILETYPE_TO_EXT)
EXT_TO_FILETYPE = {
    "py": "python",
    "pyw": "python",
    "js": "javascript",
    "mjs": "javascript",
    "jsx": "jsx",
    "ts": "typescript",
    "tsx": "tsx",
    "sh": "shell",
    "bash": "shell",
    "ps1": "powershell",
    "bat": "batch",
    "cmd": "cmd",
    "rb": "ruby",
    "php": "php",
    "go": "go",
    "java": "java",
    "kt": "kotlin",
    "kts": "kotlin",
    "scala": "scala",
    "swift": "swift",
    "rs": "rust",
    "cs": "csharp",
    "vb": "visualbasic",
    "c": "c",
    "cpp": "cpp",
    "cc": "cpp",
    "cxx": "cpp",
    "c++": "cpp",
    "h": "header",
    "hpp": "header",
    "r": "r",
    "jl": "julia",
    "pl": "perl",
    "pm": "perl",
    "hs": "haskell",
    "erl": "erlang",
    "ex": "elixir",
    "exs": "elixir",
    "clj": "clojure",
    "cljs": "clojurescript",
    "edn": "edn",
    "dart": "dart",
    "lua": "lua",
    "m": "objective-c",
    "mm": "objective-cpp",
    "mat": "matlab",
    "v": "verilog",
    "sv": "systemverilog",
    "vhd": "vhdl",
    "html": "html",
    "htm": "html",
    "css": "css",
    "xml": "xml",
    "json": "json",
    "yml": "yaml",
    "yaml": "yaml",
    "ini": "ini",
    "toml": "toml",
    "cfg": "config",
    "conf": "config",
    "env": "env",
    "md": "markdown",
    "markdown": "markdown",
    "mdown": "markdown",
    "rst": "rst",
    "tex": "tex",
    "typ": "typst",
    "typst": "typst",
    "log": "log",
    "ipynb": "jupyter",
    "csv": "csv",
    "tsv": "tsv",
    "sql": "sql",
    "sqlite": "sqlite",
    "db": "db",
    "parquet": "parquet",
    "feather": "feather",
    "avro": "avro",
    "orc": "orc",
    "yb": "yb",
    "br": "brotli",
    "pdf": "pdf",
    "doc": "word",
    "docx": "word",
    "xls": "excel",
    "xlsx": "excel",
    "ppt": "powerpoint",
    "pptx": "powerpoint",
    "zip": "zip",
    "tar": "tar",
    "gz": "gzip",
    "bz2": "bzip2",
    "xz": "xz",
    "7z": "7z",
    "rar": "rar",
    "jpg": "jpeg",
    "jpeg": "jpeg",
    "jpe": "jpeg",
    "png": "png",
    "gif": "gif",
    "bmp": "bmp",
    "tif": "tiff",
    "tiff": "tiff",
    "svg": "svg",
    "webp": "webp",
    "ico": "ico",
    "heic": "heic",
    "mp3": "mp3",
    "wav": "wav",
    "flac": "flac",
    "m4a": "m4a",
    "ogg": "ogg",
    "aac": "aac",
    "wma": "wma",
    "mp4": "mp4",
    "mkv": "mkv",
    "webm": "webm",
    "mov": "mov",
    "avi": "avi",
    "m4v": "m4v",
    "3gp": "3gp",
    "ttf": "ttf",
    "otf": "otf",
    "woff": "woff",
    "woff2": "woff2",
    "eot": "eot",
    "obj": "obj",
    "fbx": "fbx",
    "glb": "glb",
    "gltf": "gltf",
    "stl": "stl",
    "txf": "txflow",
    "draft": "draft",
    "txt": "text",
}

DOTFILE_TO_FILETYPE = {
    '.gitignore': 'gitignore',
    '.dockerignore': 'dockerignore',
    '.editorconfig': 'editorconfig',
    '.eslintrc': 'json',
    '.eslintrc.json': 'json',
    '.eslintrc.js': 'javascript',
    '.babelrc': 'json',
    '.prettierrc': 'json',
    '.prettierignore': 'ignore',
    '.npmrc': 'ini',
    '.yarnrc': 'yaml',
    '.env': 'env',
    '.env.example': 'env',
    '.env.local': 'env',
    '.env.development': 'env',
    '.env.production': 'env',
    'fish_history': 'fish_history',
    '.fish_history': 'fish_history',
    '.bashrc': 'bash',
    '.bash_profile': 'bash',
    '.zshrc': 'zsh',
    '.vimrc': 'vim',
    '.tmux.conf': 'tmux',
    '.htaccess': 'apache',
    'Dockerfile': 'dockerfile',
    'Makefile': 'makefile',
    'Rakefile': 'ruby',
    'Gemfile': 'ruby',
    'Vagrantfile': 'ruby',
    'Procfile': 'procfile',
    '.gitattributes': 'gitattributes',
    '.gitmodules': 'gitconfig',
    '.mailmap': 'mailmap',
    'requirements.txt': 'text',
    'package.json': 'json',
    'composer.json': 'json',
    'tsconfig.json': 'json',
    'webpack.config.js': 'javascript',
    'gulpfile.js': 'javascript',
    'Gruntfile.js': 'javascript',
    '.pylintrc': 'ini',
    '.flake8': 'ini',
    'setup.cfg': 'ini',
    'tox.ini': 'ini',
    '.coveragerc': 'ini',
    'pytest.ini': 'ini',
    '.travis.yml': 'yaml',
    '.gitlab-ci.yml': 'yaml',
    'docker-compose.yml': 'yaml',
    'appveyor.yml': 'yaml',
    'Cargo.toml': 'toml',
    'pyproject.toml': 'toml',
    'poetry.lock': 'toml',
    'Cargo.lock': 'toml',
    'go.mod': 'gomod',
    'go.sum': 'gosum',
}
